version: "3.9"

services:
  app:
    build: .
    image: 'server-application'
    container_name: server-app-container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rock_paper_scissors?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
      - "54555:54555/tcp"
      - "54777:54777/udp"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rock_paper_scissors
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
